- project:
    templates:
      - publish-openstack-docs-pti
    check:
      jobs:
        - devstack-plugin-nfs-tempest-full
        - devstack-plugin-nfs-tempest-full-ussuri
        - devstack-plugin-nfs-tempest-full-train
        - devstack-plugin-nfs-tempest-full-stein
    gate:
      jobs:
        - devstack-plugin-nfs-tempest-full
        - devstack-plugin-nfs-tempest-full-ussuri
        - devstack-plugin-nfs-tempest-full-train
        - devstack-plugin-nfs-tempest-full-stein

- job:
    name: devstack-plugin-nfs-tempest-full
    parent: tempest-full
    description: |
      tempest-full job based on NFS with py2.
      Former names for this job where:
        * legacy-tempest-dsvm-full-devstack-plugin-nfs
    timeout: 10800
    required-projects:
      - opendev.org/openstack/devstack-plugin-nfs
    host-vars:
      controller:
        devstack_plugins:
          devstack-plugin-nfs: https://opendev.org/openstack/devstack-plugin-nfs
    vars:
      devstack_localrc:
        ENABLE_NFS_CINDER: true
        # enabled by default in tempest-full:
        ENABLE_VOLUME_MULTIATTACH: false
    irrelevant-files: &gate-irrelevant-files
      - ^.*\.rst$
      - ^doc/.*$
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
    branches:
      - stable/ocata
      - stable/pike
      - stable/queens
      - stable/rocky
      - stable/stein
      - stable/train

- job:
    name: devstack-plugin-nfs-tempest-full
    parent: tempest-full-py3
    description: |
      tempest-full-py3 job based on NFS.
      Former names for this job where:
        * legacy-tempest-dsvm-full-devstack-plugin-nfs
    timeout: 10800
    required-projects:
      - opendev.org/openstack/devstack-plugin-nfs
    host-vars:
      controller:
        devstack_plugins:
          devstack-plugin-nfs: https://opendev.org/openstack/devstack-plugin-nfs
    vars:
      devstack_localrc:
        ENABLE_NFS_CINDER: true
        # enabled by default in tempest-full:
        ENABLE_VOLUME_MULTIATTACH: false
    irrelevant-files: *gate-irrelevant-files
    branches: ^(?!stable/(ocata|pike|queens|rocky|stein|train)).*$

- job:
    name: devstack-plugin-nfs-tempest-full-ussuri
    parent: devstack-plugin-nfs-tempest-full
    override-checkout: stable/ussuri

- job:
    name: devstack-plugin-nfs-tempest-full-train
    parent: devstack-plugin-nfs-tempest-full
    override-checkout: stable/train

- job:
    name: devstack-plugin-nfs-tempest-full-stein
    parent: devstack-plugin-nfs-tempest-full
    override-checkout: stable/stein
