- project:
    check:
      jobs:
        - devstack-plugin-nfs-tempest-full
        - devstack-plugin-nfs-tempest-full-train
        - devstack-plugin-nfs-tempest-full-stein
        - devstack-plugin-nfs-tempest-full-rocky
        - devstack-plugin-nfs-tempest-full-queens
    gate:
      jobs:
        - devstack-plugin-nfs-tempest-full
        - devstack-plugin-nfs-tempest-full-train
        - devstack-plugin-nfs-tempest-full-stein
        - devstack-plugin-nfs-tempest-full-rocky
        - devstack-plugin-nfs-tempest-full-queens

- job:
    name: devstack-plugin-nfs-tempest-full
    parent: tempest-full
    description: |
      tempest-full job based on NFS.
      Former names for this job where:
        * legacy-tempest-dsvm-full-devstack-plugin-nfs
    timeout: 10800
    required-projects:
      - opendev.org/x/devstack-plugin-nfs
    host-vars:
      controller:
        devstack_plugins:
          devstack-plugin-nfs: https://opendev.org/x/devstack-plugin-nfs
    vars:
      devstack_localrc:
        ENABLE_NFS_CINDER: true
        # enabled by default in tempest-full:
        ENABLE_VOLUME_MULTIATTACH: false
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$

- job:
    name: devstack-plugin-nfs-tempest-full-train
    parent: devstack-plugin-nfs-tempest-full
    override-checkout: stable/train
    vars:
      devstack_localrc:
        USE_PYTHON3: 'False'

- job:
    name: devstack-plugin-nfs-tempest-full-stein
    parent: devstack-plugin-nfs-tempest-full
    override-checkout: stable/stein
    vars:
      devstack_localrc:
        USE_PYTHON3: 'False'

- job:
    name: devstack-plugin-nfs-tempest-full-rocky
    parent: devstack-plugin-nfs-tempest-full
    override-checkout: stable/rocky
    vars:
      devstack_localrc:
        USE_PYTHON3: 'False'

- job:
    name: devstack-plugin-nfs-tempest-full-queens
    parent: devstack-plugin-nfs-tempest-full
    override-checkout: stable/queens
    vars:
      devstack_localrc:
        USE_PYTHON3: 'False'
