- project:
    templates:
      - publish-openstack-docs-pti
    check:
      jobs:
        - devstack-plugin-nfs-tempest-full
        - devstack-plugin-nfs-tempest-full-zed
        - devstack-plugin-nfs-tempest-full-yoga
        - devstack-plugin-nfs-tempest-full-xena
        - devstack-plugin-nfs-tempest-full-wallaby
        - devstack-plugin-nfs-tempest-full-victoria
        # ussuri disabled due to https://bugs.launchpad.net/nova/+bug/1916750
        - devstack-plugin-nfs-tempest-full-ussuri:
           voting: no
    gate:
      jobs:
        - devstack-plugin-nfs-tempest-full
        - devstack-plugin-nfs-tempest-full-zed
        - devstack-plugin-nfs-tempest-full-yoga
        - devstack-plugin-nfs-tempest-full-xena
        - devstack-plugin-nfs-tempest-full-wallaby
        - devstack-plugin-nfs-tempest-full-victoria
        # - devstack-plugin-nfs-tempest-full-ussuri

- job:
    name: devstack-plugin-nfs-tempest-full
    parent: tempest-full
    description: |
      tempest-full job based on NFS with py2.
      Former names for this job where:
        * legacy-tempest-dsvm-full-devstack-plugin-nfs
    timeout: 10800
    required-projects:
      - opendev.org/openstack/devstack-plugin-nfs
    host-vars:
      controller:
        devstack_plugins:
          devstack-plugin-nfs: https://opendev.org/openstack/devstack-plugin-nfs
    vars:
      devstack_localrc:
        ENABLE_NFS_CINDER: true
        # enabled by default in tempest-full:
        ENABLE_VOLUME_MULTIATTACH: false
    irrelevant-files: &gate-irrelevant-files
      - ^.*\.rst$
      - ^doc/.*$
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
    branches:
      - stable/ocata
      - stable/pike
      - stable/queens
      - stable/rocky
      - stable/stein
      - stable/train

- job:
    name: devstack-plugin-nfs-tempest-full
    parent: tempest-full-py3
    description: |
      tempest-full-py3 job based on NFS.
      Former names for this job where:
        * legacy-tempest-dsvm-full-devstack-plugin-nfs
    timeout: 10800
    required-projects:
      - opendev.org/openstack/devstack-plugin-nfs
    host-vars:
      controller:
        devstack_plugins:
          devstack-plugin-nfs: https://opendev.org/openstack/devstack-plugin-nfs
    vars:
      devstack_localrc:
        ENABLE_NFS_CINDER: true
        # enabled by default in tempest-full:
        ENABLE_VOLUME_MULTIATTACH: false
      devstack_services:
        # Disable horizon (inherited from the parent, not needed by the tests executed here)
        horizon: false
    irrelevant-files: *gate-irrelevant-files
    branches: ^(?!stable/(ocata|pike|queens|rocky|stein|train)).*$

- job:
    name: devstack-plugin-nfs-tempest-full-zed
    parent: devstack-plugin-nfs-tempest-full
    override-checkout: stable/zed

- job:
    name: devstack-plugin-nfs-tempest-full-yoga
    parent: devstack-plugin-nfs-tempest-full
    override-checkout: stable/yoga

- job:
    name: devstack-plugin-nfs-tempest-full-xena
    parent: devstack-plugin-nfs-tempest-full
    nodeset: openstack-single-node-focal
    override-checkout: stable/xena

- job:
    name: devstack-plugin-nfs-tempest-full-wallaby
    parent: devstack-plugin-nfs-tempest-full
    nodeset: openstack-single-node-focal
    override-checkout: stable/wallaby

- job:
    name: devstack-plugin-nfs-tempest-full-victoria
    parent: devstack-plugin-nfs-tempest-full
    nodeset: openstack-single-node-focal
    override-checkout: stable/victoria

- job:
    name: devstack-plugin-nfs-tempest-full-ussuri
    parent: devstack-plugin-nfs-tempest-full
    nodeset: openstack-single-node-bionic
    override-checkout: stable/ussuri
